#config 1
com.instana.plugin.host:
  tags:
    - 'dev'
    
# Java Profiling 1
com.instana.plugin.profiling.java:
  enabled: true

# Mysql
com.instana.plugin.mysql:
  user: 'config'
  password: 'one'
